//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deegautex
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EmployeeInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_EmployeeInfo()
        {
            this.TB_MoneyGiven = new HashSet<TB_MoneyGiven>();
            this.TB_MoneyTaking = new HashSet<TB_MoneyTaking>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<int> Phone { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public Nullable<int> GenderId { get; set; }
        public string RefarName { get; set; }
        public string R_Address { get; set; }
        public Nullable<int> R_Phone { get; set; }
    
        public virtual TB_GenderInfo TB_GenderInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MoneyGiven> TB_MoneyGiven { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_MoneyTaking> TB_MoneyTaking { get; set; }
    }
}
