//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deegautex
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MoneyTaking
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> ReceiverId { get; set; }
        public string Purpose { get; set; }
        public string Remark { get; set; }
        public Nullable<int> TotalMoney { get; set; }
        public string LoginUserName { get; set; }
    
        public virtual TB_EmployeeInfo TB_EmployeeInfo { get; set; }
    }
}
