//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deegautex
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_UserInfo
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string D { get; set; }
        public string T { get; set; }
        public string F { get; set; }
        public string A { get; set; }
        public string S { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
